/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.time.LocalDate;
import javax.swing.JPanel;
import objetos.Especialidad;
import objetos.Especialista;
import objetos.Hora;
import objetos.Institucion;
import objetos.Paciente;
import objetos.Profesional;
import objetos.Puesto;
import objetos.Turno;

/**
 *
 * @author omarit
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Institucion inst = new Institucion("\u0394 Delta",175000);
        Paciente pac1 = new Paciente("29555208", "Omar", "Roselli", "Vivorata 2968", 4379450, "OSDE", 3, false); 
        Paciente pac2 = new Paciente("36397301", "Ignacio", "Carucci", "Planes 916", 1234567, "OSMATA", 10, false);
        Paciente pac3 = new Paciente("25452831","Maria Soledad","Roselli","Scavini 2345",643169,"Medife",25,false);
        Paciente pac4 = new Paciente("05795903","Maria de los Angeles","Inclan","San Lorenzo 262",15020650,"IOMA",10,false);
        inst.agregarPaciente(pac1);
        inst.agregarPaciente(pac2);
        inst.agregarPaciente(pac3);
        inst.agregarPaciente(pac4);
        Especialista prof1 = new Especialista("31625325", "Malena", "Griffiths", "Colon 30",58744291 ,10363,Especialidad.OSTEOPATIA);
        Profesional prof2 = new Profesional("1234567","John","Doe","Fake Street 1234",1234567,101010);
        Especialista prof3 = new Especialista("38601802", "Julieta", "Della Penna", "Planes 916", 33959603, 10760, Especialidad.ATM);
        inst.agregarProfesional(prof1);
        inst.agregarProfesional(prof2);
        inst.agregarProfesional(prof3);
        Puesto p1 = new Puesto("Camilla 1");
        Puesto p2 = new Puesto("Camilla 2");
        Puesto p3 = new Puesto("Bicicleta fija");
        Puesto p4 = new Puesto("Gimnasio 1");
        Puesto p5 = new Puesto("Gimnasio 2");
        inst.addPuesto(p1);
        inst.addPuesto(p2);
        inst.addPuesto(p3);
        inst.addPuesto(p4);
        inst.addPuesto(p5);
        Turno t1 = new Turno(p5, pac4, prof3, LocalDate.of(2026,1,10), Hora.H10);
        Turno t2 = new Turno(p3, pac3, prof2, LocalDate.of(2026,1,10), Hora.H10);
        Turno t3 = new Turno(p1, pac2, prof1, LocalDate.of(2026,1,9), Hora.H10);
        Turno t4 = new Turno(p2, pac1, prof2, LocalDate.of(2026,1,9), Hora.H10);
        Turno t5 = new Turno(p2, pac2, prof1, LocalDate.of(2026,1,5), Hora.H9);
        inst.agregarTurno(t1);
        inst.agregarTurno(t2);
        inst.agregarTurno(t3);
        inst.agregarTurno(t4);
        inst.agregarTurno(t5);
        mostrarPanel(new PanelMenu(inst)); 
    }
    
    public void mostrarPanel(JPanel panel){
       contenido.removeAll();
       contenido.add(panel, BorderLayout.CENTER);
       contenido.revalidate();
       contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new PanelFondo("/images/fondo.png");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenido.setMinimumSize(new java.awt.Dimension(640, 500));
        contenido.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido;
    // End of variables declaration//GEN-END:variables
}
