package view;

import java.awt.Color;
import javax.swing.SwingUtilities;
import objetos.Institucion;

public class PacientesMenu extends javax.swing.JPanel {
    private Institucion inst;
    /**
     * Creates new form PacientesMenu
     */
    public PacientesMenu(Institucion inst) {
        this.setOpaque(false);
        initComponents();
        this.inst = inst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPacientes = new javax.swing.JLabel();
        backPac = new javax.swing.JButton();
        newPac = new javax.swing.JButton();
        searchPac = new javax.swing.JButton();
        listPac = new javax.swing.JButton();
        editPac = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tituloPacientes.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tituloPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPacientes.setText("Menu Pacientes");

        backPac.setBackground(new java.awt.Color(0, 51, 153));
        backPac.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backPac.setForeground(new java.awt.Color(255, 255, 255));
        backPac.setText("Atras");
        backPac.setToolTipText("");
        backPac.setAutoscrolls(true);
        backPac.addActionListener(this::backPacActionPerformed);

        newPac.setBackground(new java.awt.Color(203, 0, 0));
        newPac.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newPac.setForeground(new java.awt.Color(255, 255, 255));
        newPac.setText("Nuevo Paciente");
        newPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newPacMousePressed(evt);
            }
        });
        newPac.addActionListener(this::newPacActionPerformed);

        searchPac.setBackground(new java.awt.Color(203, 0, 0));
        searchPac.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchPac.setForeground(new java.awt.Color(255, 255, 255));
        searchPac.setText("Buscar Paciente");
        searchPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        searchPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchPacMousePressed(evt);
            }
        });
        searchPac.addActionListener(this::searchPacActionPerformed);

        listPac.setBackground(new java.awt.Color(203, 0, 0));
        listPac.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listPac.setForeground(new java.awt.Color(255, 255, 255));
        listPac.setText("Listar Pacientes");
        listPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        listPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listPacMousePressed(evt);
            }
        });
        listPac.addActionListener(this::listPacActionPerformed);

        editPac.setBackground(new java.awt.Color(203, 0, 0));
        editPac.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        editPac.setForeground(new java.awt.Color(255, 255, 255));
        editPac.setText("Editar Paciente");
        editPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        editPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editPacMousePressed(evt);
            }
        });
        editPac.addActionListener(this::editPacActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editPac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listPac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPac, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(286, 286, 286))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(backPac, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(tituloPacientes)
                .addGap(72, 72, 72)
                .addComponent(newPac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchPac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listPac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editPac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(backPac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPacActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PanelMenu(inst));
    }//GEN-LAST:event_backPacActionPerformed

    private void newPacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPacMousePressed
        // TODO add your handling code here:
        newPac.setBackground(new Color(158,0,0));
    }//GEN-LAST:event_newPacMousePressed

    private void newPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPacActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new NewPaciente(inst));
    }//GEN-LAST:event_newPacActionPerformed

    private void searchPacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchPacMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPacMousePressed

    private void searchPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPacActionPerformed

    private void listPacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPacMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listPacMousePressed

    private void listPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listPacActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ListPacientes(inst));
    }//GEN-LAST:event_listPacActionPerformed

    private void editPacMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPacMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPacMousePressed

    private void editPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPacActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPac;
    private javax.swing.JButton editPac;
    private javax.swing.JButton listPac;
    private javax.swing.JButton newPac;
    private javax.swing.JButton searchPac;
    private javax.swing.JLabel tituloPacientes;
    // End of variables declaration//GEN-END:variables
}
