package view;


import java.awt.Color;
import java.awt.Window;
import javax.swing.SwingUtilities;
import objetos.Institucion;

public class PanelMenu extends javax.swing.JPanel {
    
    private Institucion institucion;
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu(Institucion institucion) {
        this.setOpaque(false);
        initComponents();
        this.institucion = institucion;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pacientes = new javax.swing.JButton();
        javax.swing.JButton salir = new javax.swing.JButton();
        pacientes1 = new javax.swing.JButton();
        pacientes2 = new javax.swing.JButton();
        logoContainer = new LogoPanel("/images/Logo.png");

        setBackground(new java.awt.Color(255, 255, 255));

        pacientes.setBackground(new java.awt.Color(203, 0, 0));
        pacientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pacientes.setForeground(new java.awt.Color(255, 255, 255));
        pacientes.setText("Pacientes");
        pacientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacientesMousePressed(evt);
            }
        });
        pacientes.addActionListener(this::pacientesActionPerformed);

        salir.setBackground(new java.awt.Color(255, 0, 51));
        salir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(this::salirActionPerformed);

        pacientes1.setBackground(new java.awt.Color(203, 0, 0));
        pacientes1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pacientes1.setForeground(new java.awt.Color(255, 255, 255));
        pacientes1.setText("Profesionales");
        pacientes1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pacientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacientes1MousePressed(evt);
            }
        });
        pacientes1.addActionListener(this::pacientes1ActionPerformed);

        pacientes2.setBackground(new java.awt.Color(203, 0, 0));
        pacientes2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pacientes2.setForeground(new java.awt.Color(255, 255, 255));
        pacientes2.setText("Turnos");
        pacientes2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pacientes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacientes2MousePressed(evt);
            }
        });
        pacientes2.addActionListener(this::pacientes2ActionPerformed);

        javax.swing.GroupLayout logoContainerLayout = new javax.swing.GroupLayout(logoContainer);
        logoContainer.setLayout(logoContainerLayout);
        logoContainerLayout.setHorizontalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        logoContainerLayout.setVerticalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pacientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pacientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pacientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PacientesMenu(institucion));
    }//GEN-LAST:event_pacientesActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Window ventana = SwingUtilities.getWindowAncestor(this);
        ventana.dispose();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void pacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientesMousePressed
        // TODO add your handling code here:
        pacientes.setBackground(new Color(158,0,0));
    }//GEN-LAST:event_pacientesMousePressed

    private void pacientes1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientes1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientes1MousePressed

    private void pacientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientes1ActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ProfesionalMenu(institucion));
    }//GEN-LAST:event_pacientes1ActionPerformed

    private void pacientes2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientes2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientes2MousePressed

    private void pacientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientes2ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel logoContainer;
    private javax.swing.JButton pacientes;
    private javax.swing.JButton pacientes1;
    private javax.swing.JButton pacientes2;
    // End of variables declaration//GEN-END:variables
}
