package view;


import view.profesionales.ProfesionalMenu;
import view.pacientes.PacientesMenu;
import java.awt.Color;
import java.awt.Window;
import javax.swing.SwingUtilities;
import objetos.Institucion;
import view.Institucion.InstitucionMenu;
import view.turnos.TurnosMenu;

public class PanelMenu extends javax.swing.JPanel {
    
    private Institucion institucion;
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu(Institucion institucion) {
        this.setOpaque(false);
        initComponents();
        this.institucion = institucion;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pacientes = new javax.swing.JButton();
        javax.swing.JButton salir = new javax.swing.JButton();
        profesionales = new javax.swing.JButton();
        turnos = new javax.swing.JButton();
        logoContainer = new LogoPanel("/images/Logo.png");
        finanzas = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pacientes.setBackground(new java.awt.Color(203, 0, 0));
        pacientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pacientes.setForeground(new java.awt.Color(255, 255, 255));
        pacientes.setText("Pacientes");
        pacientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pacientesMousePressed(evt);
            }
        });
        pacientes.addActionListener(this::pacientesActionPerformed);

        salir.setBackground(new java.awt.Color(255, 0, 51));
        salir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(this::salirActionPerformed);

        profesionales.setBackground(new java.awt.Color(203, 0, 0));
        profesionales.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        profesionales.setForeground(new java.awt.Color(255, 255, 255));
        profesionales.setText("Profesionales");
        profesionales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        profesionales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                profesionalesMousePressed(evt);
            }
        });
        profesionales.addActionListener(this::profesionalesActionPerformed);

        turnos.setBackground(new java.awt.Color(203, 0, 0));
        turnos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        turnos.setForeground(new java.awt.Color(255, 255, 255));
        turnos.setText("Turnos");
        turnos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        turnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                turnosMousePressed(evt);
            }
        });
        turnos.addActionListener(this::turnosActionPerformed);

        javax.swing.GroupLayout logoContainerLayout = new javax.swing.GroupLayout(logoContainer);
        logoContainer.setLayout(logoContainerLayout);
        logoContainerLayout.setHorizontalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        logoContainerLayout.setVerticalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        finanzas.setBackground(new java.awt.Color(203, 0, 0));
        finanzas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        finanzas.setForeground(new java.awt.Color(255, 255, 255));
        finanzas.setText("Institucion");
        finanzas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        finanzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                finanzasMousePressed(evt);
            }
        });
        finanzas.addActionListener(this::finanzasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profesionales, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(profesionales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(turnos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(finanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PacientesMenu(institucion));
    }//GEN-LAST:event_pacientesActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Window ventana = SwingUtilities.getWindowAncestor(this);
        ventana.dispose();
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void pacientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pacientesMousePressed
        // TODO add your handling code here:
        pacientes.setBackground(new Color(158,0,0));
    }//GEN-LAST:event_pacientesMousePressed

    private void profesionalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesionalesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionalesMousePressed

    private void profesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionalesActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ProfesionalMenu(institucion));
    }//GEN-LAST:event_profesionalesActionPerformed

    private void turnosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_turnosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_turnosMousePressed

    private void turnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnosActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new TurnosMenu(institucion));
    }//GEN-LAST:event_turnosActionPerformed

    private void finanzasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finanzasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_finanzasMousePressed

    private void finanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finanzasActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new InstitucionMenu(institucion));
    }//GEN-LAST:event_finanzasActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finanzas;
    private javax.swing.JPanel logoContainer;
    private javax.swing.JButton pacientes;
    private javax.swing.JButton profesionales;
    private javax.swing.JButton turnos;
    // End of variables declaration//GEN-END:variables
}
