/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.Institucion;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import objetos.Institucion;
import view.MainFrame;
import view.PanelFondo;
import view.PanelMenu;

public class InstitucionMenu extends javax.swing.JPanel {
    private Institucion institucion;

    public InstitucionMenu(Institucion institucion) {
        this.institucion = institucion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelFondo("/images/fondo.png");
        atras = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        gastos = new javax.swing.JButton();
        comprobantes = new javax.swing.JButton();
        puestos = new javax.swing.JButton();
        coefEspecialista = new javax.swing.JButton();
        valorTurno = new javax.swing.JButton();
        nombreInstitucion = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 500));
        setMinimumSize(new java.awt.Dimension(720, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(720, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 500));
        jPanel1.setRequestFocusEnabled(false);

        atras.setBackground(new java.awt.Color(0, 51, 153));
        atras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");
        atras.setToolTipText("");
        atras.setAutoscrolls(true);
        atras.addActionListener(this::atrasActionPerformed);

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Menu Institucion");

        gastos.setBackground(new java.awt.Color(203, 0, 0));
        gastos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        gastos.setForeground(new java.awt.Color(255, 255, 255));
        gastos.setText("Gastos Mensuales");
        gastos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        gastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gastosMousePressed(evt);
            }
        });
        gastos.addActionListener(this::gastosActionPerformed);

        comprobantes.setBackground(new java.awt.Color(203, 0, 0));
        comprobantes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        comprobantes.setForeground(new java.awt.Color(255, 255, 255));
        comprobantes.setText("Comprobantes");
        comprobantes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        comprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comprobantesMousePressed(evt);
            }
        });
        comprobantes.addActionListener(this::comprobantesActionPerformed);

        puestos.setBackground(new java.awt.Color(203, 0, 0));
        puestos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        puestos.setForeground(new java.awt.Color(255, 255, 255));
        puestos.setText("Puestos");
        puestos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        puestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                puestosMousePressed(evt);
            }
        });
        puestos.addActionListener(this::puestosActionPerformed);

        coefEspecialista.setBackground(new java.awt.Color(203, 0, 0));
        coefEspecialista.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        coefEspecialista.setForeground(new java.awt.Color(255, 255, 255));
        coefEspecialista.setText("Coeficiente Especialista");
        coefEspecialista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        coefEspecialista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                coefEspecialistaMousePressed(evt);
            }
        });
        coefEspecialista.addActionListener(this::coefEspecialistaActionPerformed);

        valorTurno.setBackground(new java.awt.Color(203, 0, 0));
        valorTurno.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        valorTurno.setForeground(new java.awt.Color(255, 255, 255));
        valorTurno.setText("Valor Turno");
        valorTurno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        valorTurno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valorTurnoMousePressed(evt);
            }
        });
        valorTurno.addActionListener(this::valorTurnoActionPerformed);

        nombreInstitucion.setBackground(new java.awt.Color(203, 0, 0));
        nombreInstitucion.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nombreInstitucion.setForeground(new java.awt.Color(255, 255, 255));
        nombreInstitucion.setText("Nombre Institucion");
        nombreInstitucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        nombreInstitucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreInstitucionMousePressed(evt);
            }
        });
        nombreInstitucion.addActionListener(this::nombreInstitucionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(puestos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comprobantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gastos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coefEspecialista, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(valorTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreInstitucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titulo)
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valorTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(coefEspecialista, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(puestos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PanelMenu(institucion));
    }//GEN-LAST:event_atrasActionPerformed

    private void gastosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastosMousePressed

    }//GEN-LAST:event_gastosMousePressed

    private void gastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosActionPerformed

    }//GEN-LAST:event_gastosActionPerformed

    private void comprobantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprobantesMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprobantesMousePressed

    private void comprobantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comprobantesActionPerformed

    private void puestosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puestosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_puestosMousePressed

    private void puestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puestosActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new Puestos(institucion));
    }//GEN-LAST:event_puestosActionPerformed

    private void coefEspecialistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coefEspecialistaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_coefEspecialistaMousePressed

    private void coefEspecialistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coefEspecialistaActionPerformed
         try {
            double nuevoValor = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingrese nuevo valor","Coeficiente Especialista",1));
            institucion.setCoefEspecialista(nuevoValor);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error en el ingreso","Error",0);
        }
    }//GEN-LAST:event_coefEspecialistaActionPerformed

    private void valorTurnoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valorTurnoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTurnoMousePressed

    private void valorTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTurnoActionPerformed
        try {
            double nuevoValor = Double.parseDouble(JOptionPane.showInputDialog(null,"Ingrese nuevo valor","Valor Turno",1));
            institucion.setValorTurno(nuevoValor);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error en el ingreso","Error",0);
        }
    }//GEN-LAST:event_valorTurnoActionPerformed

    private void nombreInstitucionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreInstitucionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInstitucionMousePressed

    private void nombreInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInstitucionActionPerformed
        String nuevoNombre = JOptionPane.showInputDialog(null,"Ingrese nuevo nombre","Nombre de la Institucion",1);
        institucion.setNombre(nuevoNombre); 
    }//GEN-LAST:event_nombreInstitucionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton coefEspecialista;
    private javax.swing.JButton comprobantes;
    private javax.swing.JButton gastos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nombreInstitucion;
    private javax.swing.JButton puestos;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton valorTurno;
    // End of variables declaration//GEN-END:variables
}
