package view.pacientes;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import objetos.Institucion;
import objetos.Paciente;
import utils.Placeholder;
import view.MainFrame;
import view.PanelFondo;
import view.PanelMenu;

public class buscarPaciente extends javax.swing.JPanel {
    private Institucion institucion;
    private Paciente seleccionado;
    /**
     * Creates new form buscarPaciente
     */
    public buscarPaciente(Institucion institucion) {
        this.institucion = institucion;
        initComponents();
        Placeholder.setPlaceholder(campoBusqueda,"...Buscar por ID, Apellido o Nombre...");
        campoBusqueda.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                cambio();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                cambio();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                cambio();
            }
        });
    }
    
    private void cambio() {
        String texto = campoBusqueda.getText();
        Paciente[] paciente = institucion.buscarPacientePorDniApellidoNombre(texto);
        if(paciente.length == 0){
            area.setText("Paciente no encontrado");
        }else{
            if(paciente[0]!=null){
                String res = "";
                for(int i=0;i<paciente.length;i++){
                    res += (paciente[i].getApellido()+", "+paciente[i].getNombre()+"\n");
                    area.setText(res);
                }
            }else{
                area.setText("Paciente no encontrado");
            }
            
        }
        if(paciente.length ==1){
            seleccionado = paciente[0];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelFondo("/images/fondo.png");
        titulo = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        atras = new javax.swing.JButton();
        seleccionar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 500));
        setMinimumSize(new java.awt.Dimension(720, 500));
        setPreferredSize(new java.awt.Dimension(720, 500));
        setRequestFocusEnabled(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(720, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 500));

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Busqueda Paciente");

        campoBusqueda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        campoBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoBusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                campoBusquedaInputMethodTextChanged(evt);
            }
        });
        campoBusqueda.addActionListener(this::campoBusquedaActionPerformed);

        area.setColumns(20);
        area.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        atras.setBackground(new java.awt.Color(0, 51, 153));
        atras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");
        atras.setToolTipText("");
        atras.setAutoscrolls(true);
        atras.addActionListener(this::atrasActionPerformed);

        seleccionar.setBackground(new java.awt.Color(0, 153, 153));
        seleccionar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        seleccionar.setForeground(new java.awt.Color(255, 255, 255));
        seleccionar.setText("Seleccionar");
        seleccionar.addActionListener(this::seleccionarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                                .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                            .addComponent(campoBusqueda, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atras, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void campoBusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_campoBusquedaInputMethodTextChanged
 
    }//GEN-LAST:event_campoBusquedaInputMethodTextChanged

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PanelMenu(institucion));
    }//GEN-LAST:event_atrasActionPerformed

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        if(seleccionado != null){
            MainFrame main = (MainFrame)SwingUtilities.getWindowAncestor(this);
            main.mostrarPanel(new Seleccionado(institucion,seleccionado));
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar solo un paciente","Error",0);
        }
        
    }//GEN-LAST:event_seleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton atras;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton seleccionar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
