package view.pacientes;

import java.awt.Color;
import javax.swing.SwingUtilities;
import objetos.Institucion;
import view.MainFrame;
import view.PanelMenu;

public class PacientesMenu extends javax.swing.JPanel {
    private Institucion inst;
    /**
     * Creates new form PacientesMenu
     */
    public PacientesMenu(Institucion inst) {
        this.setOpaque(false);
        initComponents();
        this.inst = inst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloPacientes = new javax.swing.JLabel();
        backPac = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        listar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tituloPacientes.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tituloPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPacientes.setText("Menu Pacientes");

        backPac.setBackground(new java.awt.Color(0, 51, 153));
        backPac.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backPac.setForeground(new java.awt.Color(255, 255, 255));
        backPac.setText("Atras");
        backPac.setToolTipText("");
        backPac.setAutoscrolls(true);
        backPac.addActionListener(this::backPacActionPerformed);

        crear.setBackground(new java.awt.Color(203, 0, 0));
        crear.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        crear.setForeground(new java.awt.Color(255, 255, 255));
        crear.setText("Nuevo Paciente");
        crear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearMousePressed(evt);
            }
        });
        crear.addActionListener(this::crearActionPerformed);

        buscar.setBackground(new java.awt.Color(203, 0, 0));
        buscar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("Buscar Paciente");
        buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        buscar.addActionListener(this::buscarActionPerformed);

        listar.setBackground(new java.awt.Color(203, 0, 0));
        listar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listar.setForeground(new java.awt.Color(255, 255, 255));
        listar.setText("Listar Pacientes");
        listar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listarMousePressed(evt);
            }
        });
        listar.addActionListener(this::listarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(backPac, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(tituloPacientes)
                .addGap(40, 40, 40)
                .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(listar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(backPac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPacActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PanelMenu(inst));
    }//GEN-LAST:event_backPacActionPerformed

    private void crearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMousePressed
        // TODO add your handling code here:
        crear.setBackground(new Color(158,0,0));
    }//GEN-LAST:event_crearMousePressed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new NewPaciente(inst));
    }//GEN-LAST:event_crearActionPerformed

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMousePressed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new buscarPaciente(inst));
    }//GEN-LAST:event_buscarActionPerformed

    private void listarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarMousePressed

    private void listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ListPacientes(inst));
    }//GEN-LAST:event_listarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backPac;
    private javax.swing.JButton buscar;
    private javax.swing.JButton crear;
    private javax.swing.JButton listar;
    private javax.swing.JLabel tituloPacientes;
    // End of variables declaration//GEN-END:variables
}
