/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.profesionales;

import javax.swing.SwingUtilities;
import objetos.Institucion;
import view.MainFrame;
import view.PanelFondo;

/**
 *
 * @author omarit
 */
public class ListadoProfesional extends javax.swing.JPanel {
    private Institucion institucion;
    /**
     * Creates new form Listado
     */
    public ListadoProfesional(Institucion institucion) {
        this.institucion = institucion;
        initComponents();
        showProfesionales();
    }
    public void showProfesionales(){
        String profs = institucion.mostrarProfesionales();
        ProfesionalesArea.setText(profs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelFondo("/images/fondo.png");
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProfesionalesArea = new javax.swing.JTextArea();
        backList = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 500));
        setMinimumSize(new java.awt.Dimension(720, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(720, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("LISTADO DE PROFESIONALES");

        ProfesionalesArea.setEditable(false);
        ProfesionalesArea.setColumns(20);
        ProfesionalesArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ProfesionalesArea.setRows(5);
        ProfesionalesArea.setOpaque(false);
        jScrollPane1.setViewportView(ProfesionalesArea);

        backList.setBackground(new java.awt.Color(0, 51, 153));
        backList.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backList.setForeground(new java.awt.Color(255, 255, 255));
        backList.setText("Atras");
        backList.setToolTipText("");
        backList.setAutoscrolls(true);
        backList.addActionListener(this::backListActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(backList, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backList, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backListActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ProfesionalMenu(institucion));
    }//GEN-LAST:event_backListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ProfesionalesArea;
    private javax.swing.JButton backList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
