/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.profesionales;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import objetos.Especialidad;
import objetos.Especialista;
import objetos.Institucion;
import objetos.Profesional;
import view.MainFrame;
import view.PanelFondo;

/**
 *
 * @author omarit
 */
public class newProfesional extends javax.swing.JPanel {
    private Institucion institucion;
    /**
     * Creates new form newProfesional
     */
    public newProfesional(Institucion institucion) {
        this.institucion = institucion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelFondo("/images/fondo.png");
        nombre = new javax.swing.JTextField();
        labelNombre = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        matricula = new javax.swing.JTextField();
        labelMatricula = new javax.swing.JLabel();
        especialidad = new javax.swing.JComboBox<>();
        atras = new javax.swing.JButton();
        crear = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(720, 500));
        setMinimumSize(new java.awt.Dimension(720, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(720, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 500));

        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.addActionListener(this::nombreActionPerformed);

        labelNombre.setText("NOMBRE");

        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido.addActionListener(this::apellidoActionPerformed);

        labelApellido.setText("APELLIDO");

        labelId.setText("ID");

        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id.addActionListener(this::idActionPerformed);

        direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        direccion.setToolTipText("");
        direccion.addActionListener(this::direccionActionPerformed);

        labelDireccion.setText("DIRECCION");

        labelTelefono.setText("TELEFONO");

        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        matricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        matricula.setToolTipText("");
        matricula.addActionListener(this::matriculaActionPerformed);

        labelMatricula.setText("MATRICULA");

        especialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin especialidad", "Osteopatia", "ATM", "RPG" }));
        especialidad.addActionListener(this::especialidadActionPerformed);

        atras.setBackground(new java.awt.Color(0, 51, 153));
        atras.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atras");
        atras.setToolTipText("");
        atras.setAutoscrolls(true);
        atras.addActionListener(this::atrasActionPerformed);

        crear.setBackground(new java.awt.Color(0, 153, 153));
        crear.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        crear.setForeground(new java.awt.Color(255, 255, 255));
        crear.setText("Crear");
        crear.addActionListener(this::crearActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(labelNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(labelApellido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(labelId))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(labelTelefono))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(labelDireccion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(labelMatricula))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id)
                                    .addComponent(apellido)
                                    .addComponent(nombre)
                                    .addComponent(direccion)
                                    .addComponent(telefono)
                                    .addComponent(matricula)
                                    .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(296, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(labelMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atras, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ProfesionalMenu(institucion));
    }//GEN-LAST:event_atrasActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed

    }//GEN-LAST:event_direccionActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed

    }//GEN-LAST:event_idActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed

    }//GEN-LAST:event_apellidoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed

    }//GEN-LAST:event_nombreActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculaActionPerformed

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        /*Valido la creacion de un nuevo paciente*/
        if(institucion.validacionCreacion(Integer.parseInt(matricula.getText()),id.getText())){
            switch(especialidad.getSelectedIndex()){
                case 0:
                    Profesional profesional = new Profesional(id.getText(),nombre.getText(),apellido.getText(),direccion.getText(),Integer.parseInt(telefono.getText()),Integer.parseInt(matricula.getText()));
                    institucion.agregarProfesional(profesional);
                    break;
                case 1:
                    Especialista especialista1 = new Especialista(id.getText(),nombre.getText(),apellido.getText(),direccion.getText(),Integer.parseInt(telefono.getText()),Integer.parseInt(matricula.getText()),Especialidad.OSTEOPATIA);
                    institucion.agregarProfesional(especialista1);
                    break;
                case 2:
                    Especialista especialista2 = new Especialista(id.getText(),nombre.getText(),apellido.getText(),direccion.getText(),Integer.parseInt(telefono.getText()),Integer.parseInt(matricula.getText()),Especialidad.ATM);
                    institucion.agregarProfesional(especialista2);
                    break;
                case 3:
                    Especialista especialista3 = new Especialista(id.getText(),nombre.getText(),apellido.getText(),direccion.getText(),Integer.parseInt(telefono.getText()),Integer.parseInt(matricula.getText()),Especialidad.RPG);
                    institucion.agregarProfesional(especialista3);
                    break;
                default:
                    break;
            }
        }else{
            JOptionPane.showMessageDialog(null,"Profesional ya cargado","Error",0);
        }
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new ProfesionalMenu(institucion));
    }//GEN-LAST:event_crearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton atras;
    private javax.swing.JButton crear;
    private javax.swing.JTextField direccion;
    private javax.swing.JComboBox<String> especialidad;
    private javax.swing.JTextField id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTextField matricula;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
