/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.SwingUtilities;
import objetos.Institucion;

/**
 *
 * @author omarit
 */
public class ProfesionalMenu extends javax.swing.JPanel {
    private Institucion institucion;
    /**
     * Creates new form ProfesionalMenu
     */
    public ProfesionalMenu(Institucion institucion) {
        this.institucion = institucion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new PanelFondo("/images/fondo.png");
        tituloPacientes = new javax.swing.JLabel();
        backProf = new javax.swing.JButton();
        newProf = new javax.swing.JButton();
        searchProf = new javax.swing.JButton();
        listProf = new javax.swing.JButton();
        editProf = new javax.swing.JButton();

        tituloPacientes.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        tituloPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPacientes.setText("Menu Profesional");

        backProf.setBackground(new java.awt.Color(0, 51, 153));
        backProf.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backProf.setForeground(new java.awt.Color(255, 255, 255));
        backProf.setText("Atras");
        backProf.setToolTipText("");
        backProf.setAutoscrolls(true);
        backProf.addActionListener(this::backProfActionPerformed);

        newProf.setBackground(new java.awt.Color(203, 0, 0));
        newProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newProf.setForeground(new java.awt.Color(255, 255, 255));
        newProf.setText("Nuevo Profesional");
        newProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newProfMousePressed(evt);
            }
        });
        newProf.addActionListener(this::newProfActionPerformed);

        searchProf.setBackground(new java.awt.Color(203, 0, 0));
        searchProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchProf.setForeground(new java.awt.Color(255, 255, 255));
        searchProf.setText("Buscar Profesional");
        searchProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        searchProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchProfMousePressed(evt);
            }
        });
        searchProf.addActionListener(this::searchProfActionPerformed);

        listProf.setBackground(new java.awt.Color(203, 0, 0));
        listProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listProf.setForeground(new java.awt.Color(255, 255, 255));
        listProf.setText("Listar Profesionales");
        listProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        listProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listProfMousePressed(evt);
            }
        });
        listProf.addActionListener(this::listProfActionPerformed);

        editProf.setBackground(new java.awt.Color(203, 0, 0));
        editProf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        editProf.setForeground(new java.awt.Color(255, 255, 255));
        editProf.setText("Editar Profesional");
        editProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        editProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editProfMousePressed(evt);
            }
        });
        editProf.addActionListener(this::editProfActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(tituloPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editProf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listProf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchProf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newProf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(backProf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(tituloPacientes)
                .addGap(46, 46, 46)
                .addComponent(newProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editProf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(backProf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backProfActionPerformed
        MainFrame main = (MainFrame) SwingUtilities.getWindowAncestor(this);
        main.mostrarPanel(new PanelMenu(institucion));
    }//GEN-LAST:event_backProfActionPerformed

    private void newProfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newProfMousePressed
       
    }//GEN-LAST:event_newProfMousePressed

    private void newProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProfActionPerformed
        
    }//GEN-LAST:event_newProfActionPerformed

    private void searchProfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchProfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProfMousePressed

    private void searchProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchProfActionPerformed

    private void listProfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listProfMousePressed

    private void listProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listProfActionPerformed

    private void editProfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfMousePressed

    private void editProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editProfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backProf;
    private javax.swing.JButton editProf;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton listProf;
    private javax.swing.JButton newProf;
    private javax.swing.JButton searchProf;
    private javax.swing.JLabel tituloPacientes;
    // End of variables declaration//GEN-END:variables
}
